name = "c_strings"
description = "Manage Ada <-> C string conversions conveniently"
version = "1.0.1"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["string", "conversion", "c"]

[configuration]
disabled = true
